---
# Adapted from the example in this repo: https://github.com/kubernetes-sigs/custom-metrics-apiserver
apiVersion: v1
kind: Namespace
metadata:
  name: zoekt-custom-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zoekt-custom-metrics:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: zoekt-custom-metrics-apiserver
  namespace: zoekt-custom-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zoekt-custom-metrics-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: zoekt-custom-metrics-apiserver
  namespace: zoekt-custom-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zoekt-custom-metrics-apiserver
  name: zoekt-custom-metrics-apiserver
  namespace: zoekt-custom-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoekt-custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: zoekt-custom-metrics-apiserver
      name: zoekt-custom-metrics-apiserver
    spec:
      serviceAccountName: zoekt-custom-metrics-apiserver
      containers:
      - name: zoekt-custom-metrics-apiserver
        image: 192.168.0.174:5000/zoekt-metrics-adapter
        args:
        - /usr/local/bin/adapter
        - --secure-port=6443
        env:
        - name: TARGET_SERVICE_NAME
          value: "zoekt-webserver-service.default.svc.cluster.local"
        - name: TARGET_SERVICE_PORT
          value: "6071"
        ports:
        - containerPort: 6443
          name: https
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /tmp
          name: temp-vol
      volumes:
      - name: temp-vol
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zoekt-custom-metrics-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zoekt-custom-metrics-resource-reader
subjects:
- kind: ServiceAccount
  name: zoekt-custom-metrics-apiserver
  namespace: zoekt-custom-metrics
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: zoekt-custom-metrics-apiserver
  namespace: zoekt-custom-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: zoekt-custom-metrics-apiserver
  namespace: zoekt-custom-metrics
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: zoekt-custom-metrics-apiserver
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: zoekt-custom-metrics-apiserver
    namespace: zoekt-custom-metrics
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
spec:
  service:
    name: zoekt-custom-metrics-apiserver
    namespace: zoekt-custom-metrics
  group: custom.metrics.k8s.io
  version: v1beta2
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 200
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zoekt-custom-metrics-server-resources
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zoekt-custom-metrics-resource-reader
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpa-controller-zoekt-custom-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zoekt-custom-metrics-server-resources
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
